{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ps-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "ps-operator.fullname" . }}-leaderelection
  {{- if not (or .Values.watchNamespace .Values.watchAllNamespaces) }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "ps-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ps-operator.fullname" . }}
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "ps-operator.fullname" . }}-leaderelection
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "ps-operator.fullname" . }}
  {{- if not (or .Values.watchNamespace .Values.watchAllNamespaces) }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "ps-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ps-operator.fullname" . }}
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "ps-operator.fullname" . }}
{{- end }}
