{{- $cmName := (printf "everest-rbac") -}}
{{- $cm := (lookup "v1" "ConfigMap" (include "everest.namespace" .) $cmName ) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  namespace: {{ include  "everest.namespace" . }}
data:
  {{- if or (not $cm) .Release.IsInstall }}
  enabled: {{ .Values.server.rbac.enabled | default "false" | quote }}
  policy.csv: |
    {{- .Values.server.rbac.policy | nindent 4 }}
  {{- else }}
  enabled: {{ $cm.data.enabled | default "false" | quote }}
  policy.csv: |
    {{- index $cm.data "policy.csv" | default "" | nindent 4 }}
  {{- end }}
