apiVersion: v1
kind: Service
metadata:
  name: everest-server
  namespace: {{ include  "everest.namespace" . }}
  labels:
    app.kubernetes.io/name: everest-server
    app.kubernetes.io/component: everest-server
spec:
  selector:
    app.kubernetes.io/name: everest-server
    app.kubernetes.io/component: everest-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
